export { default as SearchBar } from './SearchBar'
export { default as Header } from './Header'
export { default as Loading } from './Loading'
export { default as Modal } from './Modal'
export { default as MovieItem } from './MovieItem'
